# Generated by Django 3.1.4 on 2022-10-08 09:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_evm', '0004_registeruser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterUser',
            new_name='RegisteredUser',
        ),
    ]
